"""Remove display_name and last_login_at from users

Revision ID: 3ed0e60c8023
Revises: f842eea9d17e
Create Date: 2025-08-20 23:30:24.902584

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed0e60c8023'
down_revision: str | Sequence[str] | None = 'f842eea9d17e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='작업 상태 (pending, processing, completed, failed)',
               existing_comment='작업 상태 (pending, running, completed, failed)',
               existing_nullable=False)
    
    # 🆕 MANUAL: users 테이블에서 updated_at 컬럼만 제거
    # (display_name, last_login_at은 이미 존재하지 않음)
    try:
        op.drop_index('idx_users_last_login', table_name='users')
    except Exception:
        pass  # 인덱스가 없으면 무시
    
    try:
        op.drop_column('users', 'display_name')
    except Exception:
        pass  # 컬럼이 없으면 무시
        
    try:
        op.drop_column('users', 'last_login_at')
    except Exception:
        pass  # 컬럼이 없으면 무시
        
    # updated_at 컬럼만 실제로 제거
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='작업 상태 (pending, running, completed, failed)',
               existing_comment='작업 상태 (pending, processing, completed, failed)',
               existing_nullable=False)
    
    # 🆕 MANUAL: 롤백 시 컬럼 복원
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), 
                                    server_default=sa.text('now()'), nullable=True, 
                                    comment="프로필 수정 일시"))
    op.add_column('users', sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), 
                                    nullable=True, comment="마지막 로그인 시간"))
    op.add_column('users', sa.Column('display_name', sa.String(length=100), 
                                    nullable=True, comment="표시 이름 (선택)"))
    
    # 인덱스 복원
    op.create_index('idx_users_last_login', 'users', ['last_login_at'], unique=False)
    # ### end Alembic commands ###