"""fix: strengthen constraints and consistency in core tables

Revision ID: 6f13884faeda
Revises: 3da9a3e1c145
Create Date: 2025-08-29 14:44:30.779101

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f13884faeda'
down_revision: str | Sequence[str] | None = '3da9a3e1c145'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_jobs', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='재시도 횟수',
               existing_server_default=sa.text('0'))
    op.alter_column('analysis_jobs', 's3_key',
               existing_type=sa.VARCHAR(length=500),
               comment='S3 객체 키',
               existing_comment='S3 객체 키 (파일 경로)',
               existing_nullable=True)
    op.alter_column('analysis_jobs', 'upload_status',
               existing_type=postgresql.ENUM('pending', 'uploading', 'completed', 'failed', name='upload_status_enum'),
               nullable=False,
               existing_comment='S3 업로드 상태',
               existing_server_default=sa.text("'pending'::upload_status_enum"))
    op.alter_column('analysis_results', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='분석 상세 데이터(JSONB)',
               existing_comment='분석 유형별 특화 데이터 저장소 (모든 상세 평가 데이터 통합)',
               existing_nullable=True)
    op.alter_column('business_plans', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='분석 상태 (pending, processing, completed, failed)',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('business_plans', 'latest_job_id',
               existing_type=sa.INTEGER(),
               comment='가장 최근 분석 작업 ID',
               existing_comment='가장 최근 분석 작업 ID (상태 조회용)',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'year',
               existing_type=sa.INTEGER(),
               comment='데이터 기준 연도',
               existing_comment='데이터의 기준 연도',
               existing_nullable=False)
    op.alter_column('competitor_analysis', 'revenue',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='연간 매출액',
               existing_comment='경쟁사 연간 매출액',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'operating_profit',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='연간 영업이익',
               existing_comment='경쟁사 연간 영업이익',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'debt_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='부채 비율',
               existing_comment='경쟁사 부채 비율',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'source',
               existing_type=sa.VARCHAR(length=255),
               comment='데이터 출처',
               existing_comment='데이터의 출처',
               existing_nullable=True)
    op.alter_column('market_analysis', 'year',
               existing_type=sa.INTEGER(),
               comment='데이터 기준 연도',
               existing_comment='데이터의 기준 연도',
               existing_nullable=False)
    op.alter_column('market_analysis', 'total_revenue',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='전체 시장 매출액',
               existing_comment='(A) 해당 연도 전체 시장 매출액',
               existing_nullable=True)
    op.alter_column('market_analysis', 'cagr',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='연평균 성장률 (%)',
               existing_comment='(A) 연평균 성장률 (%)',
               existing_nullable=True)
    op.alter_column('market_analysis', 'growth_drivers',
               existing_type=sa.TEXT(),
               comment='시장 성장 동인',
               existing_comment='(A) 시장 성장 동인',
               existing_nullable=True)
    op.alter_column('market_analysis', 'customer_group',
               existing_type=sa.VARCHAR(length=100),
               comment='주요 고객군',
               existing_comment='(C) 주요 고객군',
               existing_nullable=True)
    op.alter_column('market_analysis', 'avg_purchase_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='평균 구매 금액',
               existing_comment='(C) 평균 구매 금액',
               existing_nullable=True)
    op.alter_column('market_analysis', 'nps',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='순추천지수',
               existing_comment='(C) 순추천지수',
               existing_nullable=True)
    op.alter_column('market_analysis', 'retention_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='고객 유지율',
               existing_comment='(C) 고객 유지율',
               existing_nullable=True)
    op.alter_column('product_analysis', 'tech_level',
               existing_type=sa.VARCHAR(length=100),
               comment='기술 수준',
               existing_comment='기술적 수준',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='서비스 내부 고유 ID',
               existing_comment='서비스 내부에서 사용하는 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'total_token_usage',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='누적 토큰 사용량',
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'total_token_usage',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='누적 토큰 사용량',
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='서비스 내부에서 사용하는 고유 ID',
               existing_comment='서비스 내부 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('product_analysis', 'tech_level',
               existing_type=sa.VARCHAR(length=100),
               comment='기술적 수준',
               existing_comment='기술 수준',
               existing_nullable=True)
    op.alter_column('market_analysis', 'retention_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='(C) 고객 유지율',
               existing_comment='고객 유지율',
               existing_nullable=True)
    op.alter_column('market_analysis', 'nps',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='(C) 순추천지수',
               existing_comment='순추천지수',
               existing_nullable=True)
    op.alter_column('market_analysis', 'avg_purchase_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='(C) 평균 구매 금액',
               existing_comment='평균 구매 금액',
               existing_nullable=True)
    op.alter_column('market_analysis', 'customer_group',
               existing_type=sa.VARCHAR(length=100),
               comment='(C) 주요 고객군',
               existing_comment='주요 고객군',
               existing_nullable=True)
    op.alter_column('market_analysis', 'growth_drivers',
               existing_type=sa.TEXT(),
               comment='(A) 시장 성장 동인',
               existing_comment='시장 성장 동인',
               existing_nullable=True)
    op.alter_column('market_analysis', 'cagr',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='(A) 연평균 성장률 (%)',
               existing_comment='연평균 성장률 (%)',
               existing_nullable=True)
    op.alter_column('market_analysis', 'total_revenue',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='(A) 해당 연도 전체 시장 매출액',
               existing_comment='전체 시장 매출액',
               existing_nullable=True)
    op.alter_column('market_analysis', 'year',
               existing_type=sa.INTEGER(),
               comment='데이터의 기준 연도',
               existing_comment='데이터 기준 연도',
               existing_nullable=False)
    op.alter_column('competitor_analysis', 'source',
               existing_type=sa.VARCHAR(length=255),
               comment='데이터의 출처',
               existing_comment='데이터 출처',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'debt_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='경쟁사 부채 비율',
               existing_comment='부채 비율',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'operating_profit',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='경쟁사 연간 영업이익',
               existing_comment='연간 영업이익',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'revenue',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='경쟁사 연간 매출액',
               existing_comment='연간 매출액',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'year',
               existing_type=sa.INTEGER(),
               comment='데이터의 기준 연도',
               existing_comment='데이터 기준 연도',
               existing_nullable=False)
    op.alter_column('business_plans', 'latest_job_id',
               existing_type=sa.INTEGER(),
               comment='가장 최근 분석 작업 ID (상태 조회용)',
               existing_comment='가장 최근 분석 작업 ID',
               existing_nullable=True)
    op.alter_column('business_plans', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='분석 상태 (pending, processing, completed, failed)',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('analysis_results', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='분석 유형별 특화 데이터 저장소 (모든 상세 평가 데이터 통합)',
               existing_comment='분석 상세 데이터(JSONB)',
               existing_nullable=True)
    op.alter_column('analysis_jobs', 'upload_status',
               existing_type=postgresql.ENUM('pending', 'uploading', 'completed', 'failed', name='upload_status_enum'),
               nullable=True,
               existing_comment='S3 업로드 상태',
               existing_server_default=sa.text("'pending'::upload_status_enum"))
    op.alter_column('analysis_jobs', 's3_key',
               existing_type=sa.VARCHAR(length=500),
               comment='S3 객체 키 (파일 경로)',
               existing_comment='S3 객체 키',
               existing_nullable=True)
    op.alter_column('analysis_jobs', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='재시도 횟수',
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###