"""fix: strengthen constraints and consistency in core tables

Revision ID: 6f13884faeda
Revises: 3da9a3e1c145
Create Date: 2025-08-29 14:44:30.779101

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6f13884faeda"
down_revision: str | Sequence[str] | None = "3da9a3e1c145"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "analysis_jobs",
        "retry_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="Retry count",
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "analysis_jobs",
        "s3_key",
        existing_type=sa.VARCHAR(length=500),
        comment="S3 object key",
        existing_comment="S3 object key (file path)",
        existing_nullable=True,
    )
    op.alter_column(
        "analysis_jobs",
        "upload_status",
        existing_type=postgresql.ENUM(
            "pending", "uploading", "completed", "failed", name="upload_status_enum"
        ),
        nullable=False,
        existing_comment="S3 upload status",
        existing_server_default=sa.text("'pending'::upload_status_enum"),
    )
    op.alter_column(
        "analysis_results",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Detailed analysis data (JSONB)",
        existing_comment="Type-specific analysis data store (all detailed evaluation data)",
        existing_nullable=True,
    )
    op.alter_column(
        "business_plans",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_comment="Analysis status (pending, processing, completed, failed)",
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "business_plans",
        "latest_job_id",
        existing_type=sa.INTEGER(),
        comment="Most recent analysis job ID",
        existing_comment="Most recent analysis job ID (for status lookup)",
        existing_nullable=True,
    )
    op.alter_column(
        "competitor_analysis",
        "year",
        existing_type=sa.INTEGER(),
        comment="Data reference year",
        existing_comment="Data reference year",
        existing_nullable=False,
    )
    op.alter_column(
        "competitor_analysis",
        "revenue",
        existing_type=sa.NUMERIC(precision=20, scale=2),
        comment="Annual revenue",
        existing_comment="Competitor annual revenue",
        existing_nullable=True,
    )
    op.alter_column(
        "competitor_analysis",
        "operating_profit",
        existing_type=sa.NUMERIC(precision=20, scale=2),
        comment="Annual operating profit",
        existing_comment="Competitor annual operating profit",
        existing_nullable=True,
    )
    op.alter_column(
        "competitor_analysis",
        "debt_ratio",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="Debt ratio",
        existing_comment="Competitor debt ratio",
        existing_nullable=True,
    )
    op.alter_column(
        "competitor_analysis",
        "source",
        existing_type=sa.VARCHAR(length=255),
        comment="Data source",
        existing_comment="Data source",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "year",
        existing_type=sa.INTEGER(),
        comment="Data reference year",
        existing_comment="Data reference year",
        existing_nullable=False,
    )
    op.alter_column(
        "market_analysis",
        "total_revenue",
        existing_type=sa.NUMERIC(precision=20, scale=2),
        comment="Total market revenue",
        existing_comment="(A) Total market revenue for this year",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "cagr",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        comment="CAGR (%)",
        existing_comment="(A) CAGR (%)",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "growth_drivers",
        existing_type=sa.TEXT(),
        comment="Market growth drivers",
        existing_comment="(A) Market growth drivers",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "customer_group",
        existing_type=sa.VARCHAR(length=100),
        comment="Primary customer segment",
        existing_comment="(C) Primary customer segment",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "avg_purchase_value",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        comment="Average purchase value",
        existing_comment="(C) Average purchase value",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "nps",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        comment="Net Promoter Score (NPS)",
        existing_comment="(C) Net Promoter Score (NPS)",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "retention_rate",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        comment="Customer retention rate",
        existing_comment="(C) Customer retention rate",
        existing_nullable=True,
    )
    op.alter_column(
        "product_analysis",
        "tech_level",
        existing_type=sa.VARCHAR(length=100),
        comment="Technology level",
        existing_comment="Technology level (legacy)",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        comment="Internal unique ID",
        existing_comment="Internal unique ID (legacy)",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "users",
        "total_token_usage",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="Cumulative token usage",
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "total_token_usage",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="Cumulative token usage",
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        comment="Internal unique ID (legacy)",
        existing_comment="Internal unique ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "product_analysis",
        "tech_level",
        existing_type=sa.VARCHAR(length=100),
        comment="Technology level (legacy)",
        existing_comment="Technology level",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "retention_rate",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        comment="(C) Customer retention rate",
        existing_comment="Customer retention rate",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "nps",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        comment="(C) Net Promoter Score (NPS)",
        existing_comment="Net Promoter Score (NPS)",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "avg_purchase_value",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        comment="(C) Average purchase value",
        existing_comment="Average purchase value",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "customer_group",
        existing_type=sa.VARCHAR(length=100),
        comment="(C) Primary customer segment",
        existing_comment="Primary customer segment",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "growth_drivers",
        existing_type=sa.TEXT(),
        comment="(A) Market growth drivers",
        existing_comment="Market growth drivers",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "cagr",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        comment="(A) CAGR (%)",
        existing_comment="CAGR (%)",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "total_revenue",
        existing_type=sa.NUMERIC(precision=20, scale=2),
        comment="(A) Total market revenue for this year",
        existing_comment="Total market revenue",
        existing_nullable=True,
    )
    op.alter_column(
        "market_analysis",
        "year",
        existing_type=sa.INTEGER(),
        comment="Data reference year",
        existing_comment="Data reference year",
        existing_nullable=False,
    )
    op.alter_column(
        "competitor_analysis",
        "source",
        existing_type=sa.VARCHAR(length=255),
        comment="Data source",
        existing_comment="Data source",
        existing_nullable=True,
    )
    op.alter_column(
        "competitor_analysis",
        "debt_ratio",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="Competitor debt ratio",
        existing_comment="Debt ratio",
        existing_nullable=True,
    )
    op.alter_column(
        "competitor_analysis",
        "operating_profit",
        existing_type=sa.NUMERIC(precision=20, scale=2),
        comment="Competitor annual operating profit",
        existing_comment="Annual operating profit",
        existing_nullable=True,
    )
    op.alter_column(
        "competitor_analysis",
        "revenue",
        existing_type=sa.NUMERIC(precision=20, scale=2),
        comment="Competitor annual revenue",
        existing_comment="Annual revenue",
        existing_nullable=True,
    )
    op.alter_column(
        "competitor_analysis",
        "year",
        existing_type=sa.INTEGER(),
        comment="Data reference year",
        existing_comment="Data reference year",
        existing_nullable=False,
    )
    op.alter_column(
        "business_plans",
        "latest_job_id",
        existing_type=sa.INTEGER(),
        comment="Most recent analysis job ID (for status lookup)",
        existing_comment="Most recent analysis job ID",
        existing_nullable=True,
    )
    op.alter_column(
        "business_plans",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_comment="Analysis status (pending, processing, completed, failed)",
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "analysis_results",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Type-specific analysis data store (all detailed evaluation data)",
        existing_comment="Detailed analysis data (JSONB)",
        existing_nullable=True,
    )
    op.alter_column(
        "analysis_jobs",
        "upload_status",
        existing_type=postgresql.ENUM(
            "pending", "uploading", "completed", "failed", name="upload_status_enum"
        ),
        nullable=True,
        existing_comment="S3 upload status",
        existing_server_default=sa.text("'pending'::upload_status_enum"),
    )
    op.alter_column(
        "analysis_jobs",
        "s3_key",
        existing_type=sa.VARCHAR(length=500),
        comment="S3 object key (file path)",
        existing_comment="S3 object key",
        existing_nullable=True,
    )
    op.alter_column(
        "analysis_jobs",
        "retry_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="Retry count",
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
