"""perf_add_indexes_for_api_optimization

Revision ID: a4763af9a95f
Revises: 55c6764cf05f
Create Date: 2025-08-14 23:36:25.829038

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4763af9a95f'
down_revision: str | Sequence[str] | None = '55c6764cf05f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('is_latest', sa.Boolean(), server_default='false', nullable=True, comment='해당 파일의 최신 분석 여부'))
    op.alter_column('analysis_jobs', 'job_type',
               existing_type=sa.VARCHAR(length=50),
               comment='분석 유형 (basic, market, industry 등)',
               existing_comment='분석 유형 (basic, market 등)',
               existing_nullable=False)
    op.create_index('idx_analysis_jobs_job_type', 'analysis_jobs', ['job_type'], unique=False)
    op.create_index('idx_analysis_jobs_plan_latest', 'analysis_jobs', ['plan_id', 'is_latest'], unique=False)
    op.create_index('idx_analysis_jobs_plan_type_latest', 'analysis_jobs', ['plan_id', 'job_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_analysis_jobs_status_created', 'analysis_jobs', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_analysis_jobs_type_completed', 'analysis_jobs', ['job_type', 'status', sa.literal_column('completed_at DESC')], unique=False)
    op.create_index('idx_analysis_jobs_type_status', 'analysis_jobs', ['job_type', 'status'], unique=False)
    op.add_column('analysis_results', sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='GET /analysis/sources - 자료 출처 목록'))
    op.add_column('analysis_results', sa.Column('feedback_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='GET /analysis/feedback - 개선점 목록'))
    op.add_column('analysis_results', sa.Column('bmc_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='GET /analysis/bmc - 비즈니스 모델 캔버스 데이터'))
    op.add_column('analysis_results', sa.Column('visualization_path', sa.String(length=500), nullable=True, comment='GET /analysis/visualization - 시각화 자료 경로'))
    op.alter_column('analysis_results', 'evaluation_type',
               existing_type=sa.VARCHAR(length=50),
               comment='평가 유형 (overall, market, industry, feedback 등)',
               existing_comment='평가 유형 (overall, market 등)',
               existing_nullable=False)
    op.drop_index(op.f('idx_analysis_results_importance'), table_name='analysis_results')
    op.drop_index(op.f('idx_analysis_results_confidence'), table_name='analysis_results')
    op.create_index('idx_analysis_results_confidence', 'analysis_results', [sa.literal_column('confidence_score DESC')], unique=False)
    op.create_index('idx_analysis_results_bmc_gin', 'analysis_results', ['bmc_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_analysis_results_feedback_gin', 'analysis_results', ['feedback_points'], unique=False, postgresql_using='gin')
    op.create_index('idx_analysis_results_importance_score', 'analysis_results', ['importance_level', sa.literal_column('score DESC')], unique=False)
    op.create_index('idx_analysis_results_job_score', 'analysis_results', ['analysis_job_id', sa.literal_column('score DESC')], unique=False)
    op.create_index('idx_analysis_results_sources_gin', 'analysis_results', ['sources'], unique=False, postgresql_using='gin')
    op.create_index('idx_analysis_results_type_score', 'analysis_results', ['evaluation_type', sa.literal_column('score DESC')], unique=False)
    op.add_column('business_plans', sa.Column('is_selected', sa.Boolean(), server_default='false', nullable=True, comment='현재 선택된 파일 여부 (PATCH /files/{id}/select)'))
    op.add_column('business_plans', sa.Column('sort_priority', sa.Integer(), server_default='0', nullable=True, comment='정렬 우선순위'))
    op.create_index('idx_business_plans_filename_search', 'business_plans', ['file_name'], unique=False)
    op.create_index('idx_business_plans_selected', 'business_plans', ['user_id', 'is_selected'], unique=False)
    op.create_index('idx_business_plans_sort', 'business_plans', ['user_id', 'sort_priority', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_business_plans_status_updated', 'business_plans', ['status', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_business_plans_user_created', 'business_plans', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('competitor_analysis', 'revenue',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='경쟁사 연간 매출액',
               existing_comment='(B-1) 해당 경쟁사의 연간 매출액',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'operating_profit',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='경쟁사 연간 영업이익',
               existing_comment='(B-1) 해당 경쟁사의 연간 영업이익',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'debt_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='경쟁사 부채 비율',
               existing_comment='(B-1) 해당 경쟁사의 부채 비율 (%)',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'share_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='시장 점유율',
               existing_comment='(B-2) 해당 시장에서의 점유율 (%)',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'competitive_advantage',
               existing_type=sa.TEXT(),
               comment='경쟁 우위 요소',
               existing_comment='(B-4) 경쟁 우위 요소 (특허, 브랜드, 유통망 등)',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 업데이트 시간',
               existing_comment='이 행(row)이 마지막으로 업데이트된 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_competitor_analysis_last_updated'), table_name='competitor_analysis')
    op.drop_index(op.f('idx_competitor_analysis_market_year'), table_name='competitor_analysis')
    op.create_index('idx_competitor_analysis_market_year', 'competitor_analysis', ['market_name', sa.literal_column('year DESC')], unique=False)
    op.drop_index(op.f('idx_competitor_analysis_revenue_desc'), table_name='competitor_analysis')
    op.create_index('idx_competitor_analysis_revenue_desc', 'competitor_analysis', [sa.literal_column('revenue DESC')], unique=False)
    op.drop_index(op.f('idx_competitor_analysis_share_desc'), table_name='competitor_analysis')
    op.create_index('idx_competitor_analysis_share_desc', 'competitor_analysis', [sa.literal_column('share_percentage DESC')], unique=False)
    op.add_column('market_analysis', sa.Column('industry_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='업종 트렌드 데이터'))
    op.add_column('market_analysis', sa.Column('market_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='시장 상황 데이터'))
    op.alter_column('market_analysis', 'growth_drivers',
               existing_type=sa.TEXT(),
               comment='(A) 시장 성장 동인',
               existing_comment='(A) 시장 성장 동인 (기술 트렌드, 규제 변화 등)',
               existing_nullable=True)
    op.alter_column('market_analysis', 'customer_group',
               existing_type=sa.VARCHAR(length=100),
               comment='(C) 주요 고객군',
               existing_comment='(C) 주요 고객군 (연령, 산업, 지역 등)',
               existing_nullable=True)
    op.alter_column('market_analysis', 'nps',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='(C) 순추천지수',
               existing_comment='(C) 순추천지수 (Net Promoter Score)',
               existing_nullable=True)
    op.alter_column('market_analysis', 'retention_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='(C) 고객 유지율',
               existing_comment='(C) 고객 유지율 (%)',
               existing_nullable=True)
    op.alter_column('market_analysis', 'source',
               existing_type=sa.VARCHAR(length=255),
               comment='데이터의 출처',
               existing_comment='데이터의 출처 (보고서, 기사 등)',
               existing_nullable=True)
    op.alter_column('market_analysis', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 업데이트 시간',
               existing_comment='이 행(row)이 마지막으로 업데이트된 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_market_analysis_last_updated'), table_name='market_analysis')
    op.drop_index(op.f('idx_market_analysis_year_desc'), table_name='market_analysis')
    op.drop_index(op.f('idx_market_analysis_market_year'), table_name='market_analysis')
    op.create_index('idx_market_analysis_market_year', 'market_analysis', ['market_name', sa.literal_column('year DESC')], unique=False)
    op.drop_index(op.f('idx_market_analysis_revenue_desc'), table_name='market_analysis')
    op.create_index('idx_market_analysis_revenue_desc', 'market_analysis', [sa.literal_column('total_revenue DESC')], unique=False)
    op.create_index('idx_market_analysis_conditions_gin', 'market_analysis', ['market_conditions'], unique=False, postgresql_using='gin')
    op.create_index('idx_market_analysis_trends_gin', 'market_analysis', ['industry_trends'], unique=False, postgresql_using='gin')
    op.create_index('idx_market_analysis_updated', 'market_analysis', [sa.literal_column('last_updated DESC')], unique=False)
    op.alter_column('product_analysis', 'competitor_name',
               existing_type=sa.VARCHAR(length=255),
               comment='제품 소유 경쟁사',
               existing_comment='이 제품을 소유한 경쟁사 이름',
               existing_nullable=False)
    op.alter_column('product_analysis', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment='제품명',
               existing_comment='제품 또는 서비스의 이름',
               existing_nullable=False)
    op.alter_column('product_analysis', 'price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='대표 가격',
               existing_comment='(D) 대표 가격 정보',
               existing_nullable=True)
    op.alter_column('product_analysis', 'price_policy_notes',
               existing_type=sa.TEXT(),
               comment='가격 정책 설명',
               existing_comment='(D) 가격 정책에 대한 상세 설명',
               existing_nullable=True)
    op.alter_column('product_analysis', 'distribution_channels',
               existing_type=sa.TEXT(),
               comment='유통 채널',
               existing_comment='(D) 주요 유통 채널 목록 (콤마로 구분된 텍스트 등)',
               existing_nullable=True)
    op.alter_column('product_analysis', 'tech_level',
               existing_type=sa.VARCHAR(length=100),
               comment='기술적 수준',
               existing_comment='(B-3) 제품의 기술적 수준',
               existing_nullable=True)
    op.alter_column('product_analysis', 'features',
               existing_type=sa.TEXT(),
               comment='주요 특징',
               existing_comment='(B-3) 제품의 주요 특징 요약',
               existing_nullable=True)
    op.alter_column('product_analysis', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 업데이트 시간',
               existing_comment='이 행(row)이 마지막으로 업데이트된 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_product_analysis_last_updated'), table_name='product_analysis')
    op.drop_index(op.f('idx_product_analysis_price_desc'), table_name='product_analysis')
    op.create_index('idx_product_analysis_price_desc', 'product_analysis', [sa.literal_column('price DESC')], unique=False)
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True, comment='표시 이름 (선택)'))
    op.add_column('users', sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='마지막 로그인 시간'))
    op.alter_column('users', 'cognito_sub',
               existing_type=sa.VARCHAR(length=255),
               comment='Cognito 사용자 고유 식별자 (JWT sub)',
               existing_comment='Cognito 사용자 고유 식별자',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='서비스 프로필 생성 일시',
               existing_comment='서비스 DB에 프로필 생성 일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_users_last_login', 'users', ['last_login_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_last_login', table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='서비스 DB에 프로필 생성 일시',
               existing_comment='서비스 프로필 생성 일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'cognito_sub',
               existing_type=sa.VARCHAR(length=255),
               comment='Cognito 사용자 고유 식별자',
               existing_comment='Cognito 사용자 고유 식별자 (JWT sub)',
               existing_nullable=False)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'display_name')
    op.drop_index('idx_product_analysis_price_desc', table_name='product_analysis')
    op.create_index(op.f('idx_product_analysis_price_desc'), 'product_analysis', ['price'], unique=False)
    op.create_index(op.f('idx_product_analysis_last_updated'), 'product_analysis', ['last_updated'], unique=False)
    op.alter_column('product_analysis', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='이 행(row)이 마지막으로 업데이트된 시간',
               existing_comment='마지막 업데이트 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_analysis', 'features',
               existing_type=sa.TEXT(),
               comment='(B-3) 제품의 주요 특징 요약',
               existing_comment='주요 특징',
               existing_nullable=True)
    op.alter_column('product_analysis', 'tech_level',
               existing_type=sa.VARCHAR(length=100),
               comment='(B-3) 제품의 기술적 수준',
               existing_comment='기술적 수준',
               existing_nullable=True)
    op.alter_column('product_analysis', 'distribution_channels',
               existing_type=sa.TEXT(),
               comment='(D) 주요 유통 채널 목록 (콤마로 구분된 텍스트 등)',
               existing_comment='유통 채널',
               existing_nullable=True)
    op.alter_column('product_analysis', 'price_policy_notes',
               existing_type=sa.TEXT(),
               comment='(D) 가격 정책에 대한 상세 설명',
               existing_comment='가격 정책 설명',
               existing_nullable=True)
    op.alter_column('product_analysis', 'price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='(D) 대표 가격 정보',
               existing_comment='대표 가격',
               existing_nullable=True)
    op.alter_column('product_analysis', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment='제품 또는 서비스의 이름',
               existing_comment='제품명',
               existing_nullable=False)
    op.alter_column('product_analysis', 'competitor_name',
               existing_type=sa.VARCHAR(length=255),
               comment='이 제품을 소유한 경쟁사 이름',
               existing_comment='제품 소유 경쟁사',
               existing_nullable=False)
    op.drop_index('idx_market_analysis_updated', table_name='market_analysis')
    op.drop_index('idx_market_analysis_trends_gin', table_name='market_analysis', postgresql_using='gin')
    op.drop_index('idx_market_analysis_conditions_gin', table_name='market_analysis', postgresql_using='gin')
    op.drop_index('idx_market_analysis_revenue_desc', table_name='market_analysis')
    op.create_index(op.f('idx_market_analysis_revenue_desc'), 'market_analysis', ['total_revenue'], unique=False)
    op.drop_index('idx_market_analysis_market_year', table_name='market_analysis')
    op.create_index(op.f('idx_market_analysis_market_year'), 'market_analysis', ['market_name', 'year'], unique=False)
    op.create_index(op.f('idx_market_analysis_year_desc'), 'market_analysis', ['year'], unique=False)
    op.create_index(op.f('idx_market_analysis_last_updated'), 'market_analysis', ['last_updated'], unique=False)
    op.alter_column('market_analysis', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='이 행(row)이 마지막으로 업데이트된 시간',
               existing_comment='마지막 업데이트 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_analysis', 'source',
               existing_type=sa.VARCHAR(length=255),
               comment='데이터의 출처 (보고서, 기사 등)',
               existing_comment='데이터의 출처',
               existing_nullable=True)
    op.alter_column('market_analysis', 'retention_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='(C) 고객 유지율 (%)',
               existing_comment='(C) 고객 유지율',
               existing_nullable=True)
    op.alter_column('market_analysis', 'nps',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='(C) 순추천지수 (Net Promoter Score)',
               existing_comment='(C) 순추천지수',
               existing_nullable=True)
    op.alter_column('market_analysis', 'customer_group',
               existing_type=sa.VARCHAR(length=100),
               comment='(C) 주요 고객군 (연령, 산업, 지역 등)',
               existing_comment='(C) 주요 고객군',
               existing_nullable=True)
    op.alter_column('market_analysis', 'growth_drivers',
               existing_type=sa.TEXT(),
               comment='(A) 시장 성장 동인 (기술 트렌드, 규제 변화 등)',
               existing_comment='(A) 시장 성장 동인',
               existing_nullable=True)
    op.drop_column('market_analysis', 'market_conditions')
    op.drop_column('market_analysis', 'industry_trends')
    op.drop_index('idx_competitor_analysis_share_desc', table_name='competitor_analysis')
    op.create_index(op.f('idx_competitor_analysis_share_desc'), 'competitor_analysis', ['share_percentage'], unique=False)
    op.drop_index('idx_competitor_analysis_revenue_desc', table_name='competitor_analysis')
    op.create_index(op.f('idx_competitor_analysis_revenue_desc'), 'competitor_analysis', ['revenue'], unique=False)
    op.drop_index('idx_competitor_analysis_market_year', table_name='competitor_analysis')
    op.create_index(op.f('idx_competitor_analysis_market_year'), 'competitor_analysis', ['market_name', 'year'], unique=False)
    op.create_index(op.f('idx_competitor_analysis_last_updated'), 'competitor_analysis', ['last_updated'], unique=False)
    op.alter_column('competitor_analysis', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='이 행(row)이 마지막으로 업데이트된 시간',
               existing_comment='마지막 업데이트 시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('competitor_analysis', 'competitive_advantage',
               existing_type=sa.TEXT(),
               comment='(B-4) 경쟁 우위 요소 (특허, 브랜드, 유통망 등)',
               existing_comment='경쟁 우위 요소',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'share_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='(B-2) 해당 시장에서의 점유율 (%)',
               existing_comment='시장 점유율',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'debt_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='(B-1) 해당 경쟁사의 부채 비율 (%)',
               existing_comment='경쟁사 부채 비율',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'operating_profit',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='(B-1) 해당 경쟁사의 연간 영업이익',
               existing_comment='경쟁사 연간 영업이익',
               existing_nullable=True)
    op.alter_column('competitor_analysis', 'revenue',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='(B-1) 해당 경쟁사의 연간 매출액',
               existing_comment='경쟁사 연간 매출액',
               existing_nullable=True)
    op.drop_index('idx_business_plans_user_created', table_name='business_plans')
    op.drop_index('idx_business_plans_status_updated', table_name='business_plans')
    op.drop_index('idx_business_plans_sort', table_name='business_plans')
    op.drop_index('idx_business_plans_selected', table_name='business_plans')
    op.drop_index('idx_business_plans_filename_search', table_name='business_plans')
    op.drop_column('business_plans', 'sort_priority')
    op.drop_column('business_plans', 'is_selected')
    op.drop_index('idx_analysis_results_type_score', table_name='analysis_results')
    op.drop_index('idx_analysis_results_sources_gin', table_name='analysis_results', postgresql_using='gin')
    op.drop_index('idx_analysis_results_job_score', table_name='analysis_results')
    op.drop_index('idx_analysis_results_importance_score', table_name='analysis_results')
    op.drop_index('idx_analysis_results_feedback_gin', table_name='analysis_results', postgresql_using='gin')
    op.drop_index('idx_analysis_results_bmc_gin', table_name='analysis_results', postgresql_using='gin')
    op.drop_index('idx_analysis_results_confidence', table_name='analysis_results')
    op.create_index(op.f('idx_analysis_results_confidence'), 'analysis_results', ['confidence_score'], unique=False)
    op.create_index(op.f('idx_analysis_results_importance'), 'analysis_results', ['importance_level'], unique=False)
    op.alter_column('analysis_results', 'evaluation_type',
               existing_type=sa.VARCHAR(length=50),
               comment='평가 유형 (overall, market 등)',
               existing_comment='평가 유형 (overall, market, industry, feedback 등)',
               existing_nullable=False)
    op.drop_column('analysis_results', 'visualization_path')
    op.drop_column('analysis_results', 'bmc_data')
    op.drop_column('analysis_results', 'feedback_points')
    op.drop_column('analysis_results', 'sources')
    op.drop_index('idx_analysis_jobs_type_status', table_name='analysis_jobs')
    op.drop_index('idx_analysis_jobs_type_completed', table_name='analysis_jobs')
    op.drop_index('idx_analysis_jobs_status_created', table_name='analysis_jobs')
    op.drop_index('idx_analysis_jobs_plan_type_latest', table_name='analysis_jobs')
    op.drop_index('idx_analysis_jobs_plan_latest', table_name='analysis_jobs')
    op.drop_index('idx_analysis_jobs_job_type', table_name='analysis_jobs')
    op.alter_column('analysis_jobs', 'job_type',
               existing_type=sa.VARCHAR(length=50),
               comment='분석 유형 (basic, market 등)',
               existing_comment='분석 유형 (basic, market, industry 등)',
               existing_nullable=False)
    op.drop_column('analysis_jobs', 'is_latest')
    # ### end Alembic commands ###