"""feat: add latest_job_id foreign key to business_plans

Revision ID: 3da9a3e1c145
Revises: 1288367832cd
Create Date: 2025-08-29 13:37:21.342226

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da9a3e1c145'
down_revision: str | Sequence[str] | None = '1288367832cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_plans', sa.Column('latest_job_id', sa.Integer(), nullable=True, comment='가장 최근 분석 작업 ID (상태 조회용)'))
    op.create_index('idx_business_plans_latest_job', 'business_plans', ['latest_job_id'], unique=False)
    op.create_foreign_key(None, 'business_plans', 'analysis_jobs', ['latest_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_plans', type_='foreignkey')
    op.drop_index('idx_business_plans_latest_job', table_name='business_plans')
    op.drop_column('business_plans', 'latest_job_id')
    # ### end Alembic commands ###