"""feat: add gemini integration fields

Revision ID: ebd1084c8d48
Revises: 43af05e94fe9
Create Date: 2025-08-01 XX:XX:XX.XXXXXX

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers
revision: str = 'ebd1084c8d48'
down_revision: Union[str, None] = '43af05e94fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Add new columns and performance indexes."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🔧 새 컬럼 추가 (Gemini 연동을 위한 필드들)
    op.add_column('analyses', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('analyses', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('gemini_request_id', sa.String(length=100), nullable=True))
    op.add_column('analyses', sa.Column('token_usage', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('processing_time_seconds', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('analyses', sa.Column('raw_analysis_s3_path', sa.String(length=500), nullable=True))
    op.add_column('analyses', sa.Column('raw_file_content_s3_path', sa.String(length=500), nullable=True))
    op.add_column('analyses', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    
    # ### end Alembic commands ###
    
    # 🚀 성능 최적화 인덱스 생성
    # 가장 중요한 단일 인덱스들
    op.create_index('idx_analyses_status', 'analyses', ['status'])
    op.create_index('idx_analyses_plan_id', 'analyses', ['plan_id'])  
    op.create_index('idx_analyses_gemini_request_id', 'analyses', ['gemini_request_id'])
    
    # 복합 인덱스 (자주 함께 조회되는 필드들)
    op.create_index('idx_analyses_plan_status', 'analyses', ['plan_id', 'status'])
    op.create_index('idx_analyses_status_created', 'analyses', ['status', 'created_at'])
    
    # 시간 기반 조회 최적화
    op.create_index('idx_analyses_created_at_desc', 'analyses', [sa.text('created_at DESC')])
    op.create_index('idx_analyses_completed_at_desc', 'analyses', [sa.text('completed_at DESC')], 
                   postgresql_where=sa.text('completed_at IS NOT NULL'))
    
    # 점수 기반 조회 최적화 
    op.create_index('idx_analyses_overall_score_desc', 'analyses', [sa.text('overall_score DESC')],
                   postgresql_where=sa.text('overall_score IS NOT NULL'))
    
    # 에러 처리 및 재시도 관련
    op.create_index('idx_analyses_retry_count', 'analyses', ['retry_count'],
                   postgresql_where=sa.text('retry_count > 0'))
    
    # 기본값 설정을 위한 UPDATE (기존 레코드가 있을 경우)
    op.execute("UPDATE analyses SET status = 'pending' WHERE status IS NULL")
    op.execute("UPDATE analyses SET progress = 0 WHERE progress IS NULL")
    op.execute("UPDATE analyses SET retry_count = 0 WHERE retry_count IS NULL")


def downgrade() -> None:
    """Downgrade schema - Remove indexes and columns."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🗑️ 인덱스 삭제 (컬럼 삭제 전에 먼저!)
    op.drop_index('idx_analyses_retry_count', table_name='analyses')
    op.drop_index('idx_analyses_overall_score_desc', table_name='analyses')
    op.drop_index('idx_analyses_completed_at_desc', table_name='analyses')
    op.drop_index('idx_analyses_created_at_desc', table_name='analyses')
    op.drop_index('idx_analyses_status_created', table_name='analyses')
    op.drop_index('idx_analyses_plan_status', table_name='analyses')
    op.drop_index('idx_analyses_gemini_request_id', table_name='analyses')
    op.drop_index('idx_analyses_plan_id', table_name='analyses')
    op.drop_index('idx_analyses_status', table_name='analyses')
    
    # 🗑️ 컬럼 삭제
    op.drop_column('analyses', 'completed_at')
    op.drop_column('analyses', 'retry_count')
    op.drop_column('analyses', 'error_message')
    op.drop_column('analyses', 'raw_file_content_s3_path')
    op.drop_column('analyses', 'raw_analysis_s3_path')
    op.drop_column('analyses', 'overall_score')
    op.drop_column('analyses', 'processing_time_seconds')
    op.drop_column('analyses', 'token_usage')
    op.drop_column('analyses', 'gemini_request_id')
    op.drop_column('analyses', 'progress')
    op.drop_column('analyses', 'status')
    
    # ### end Alembic commands ###