name: CI

on:
  push:
    branches: [ "feature" ]         # feature 브랜치에 push될 때 실행
  pull_request:
    branches: [ "feature" ]         # feature 브랜치로 PR 생성/업데이트 시 실행
  workflow_dispatch:                # 수동 실행 지원

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python 3.11 with uv
        run: uv python install 3.11

      - name: Sync dependencies
        run: uv sync

      - name: Create .env file               # ✅ 추가됨: GitHub Secret 기반으로 .env 파일 생성
        run: echo "${{ secrets.ENV_FILE }}" | tr '\n' '\n' > .env

      - name: Install uv audit
        run: uv pip install uv-audit

      - name: Create .env file
        run: |
          echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" > .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env

      - name: Ruff Lint
        continue-on-error: true   # ✅ 실패해도 멈추지 않도록 설정
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github .
                                    # 5. Ruff로 코드 린트 검사

      - name: Ruff Format Check
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check .    # 6. Ruff로 코드 포맷 검사

      - name: Run uv audit
        run: uv run uv-audit

      - name: Run Pytest
        run: uv run pytest

      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .
